# client/Dockerfile

# Pull the official base image
FROM node:20.9.0-alpine as build
# Set the working directory
WORKDIR /usr/src/app

# Add /usr/src/app/node_modules/.bin to the $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install app dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install --production

# Copy project files
COPY . .

# Build the React app
RUN yarn build

# Nginx stage
FROM nginx:alpine
# Copy static assets
COPY --from=build /app/build /usr/share/nginx/html
# Remove default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf
# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copy the script to start Nginx with dynamic port binding
COPY start-nginx.sh /start-nginx.sh
RUN chmod +x /start-nginx.sh
CMD ["/start-nginx.sh"]
