# client/Dockerfile

# Pull the official base image
FROM node:20.9.0-alpine as build
# Set the working directory
WORKDIR /usr/src/app

# Add /usr/src/app/node_modules/.bin to the $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install app dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install --production

# Copy project files
COPY . .

# Build the React app
RUN yarn build

# Start a new stage from scratch
FROM nginx:alpine

# Copy the built app to Nginx's serve directory
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy a new configuration file
COPY nginx.conf /etc/nginx/conf.d

# Expose the port Nginx is listening on
EXPOSE 80

# Start Nginx when the container has provisioned
CMD ["nginx", "-g", "daemon off;"]
