# client/Dockerfile

# Pull the official base image
FROM node:19.0-alpine

# Set the working directory
WORKDIR /usr/src/app

# Add /usr/src/app/node_modules/.bin to the $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install app dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install --production

# Copy project files
COPY . .

# Build the React app
RUN yarn build

# Install serve globally
RUN yarn global add serve

# Expose the port your app runs on
EXPOSE 5000

# Serve the app
CMD ["serve", "-s", "build"]
